name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Load project.env file
        run: |
          set -a
          source project.env
          set +a
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Compile into binary
        run: deno task build-all-arch
      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > SHA256SUMS.txt || shasum -a 256 * > SHA256SUMS.txt
      - name: Publish GitHub Release (multi-asset)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          fail_on_missing: true
          files: |
            dist/${{ env.BINARY_NAME }}-*
            dist/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
